# Generated by Django 6.0.7 on 2026-07-20 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('activo_afectado', models.CharField(max_length=200)),
                ('impacto', models.PositiveSmallIntegerField()),
                ('probabilidad', models.PositiveSmallIntegerField()),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], editable=False, max_length=10)),
                ('estado', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('MITIGADO', 'Mitigado'), ('ACEPTADO', 'Aceptado')], default='IDENTIFICADO', max_length=20)),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMitigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mitigacion', to='riesgos.riesgo')),
            ],
        ),
    ]
